// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3U5IB5Gy2iz8JnDdZjKtUhM8vEncG728',
    appId: '1:133788893267:web:3d83d7c64a43382b0b06a6',
    messagingSenderId: '133788893267',
    projectId: 'paysync-329b1',
    authDomain: 'paysync-329b1.firebaseapp.com',
    storageBucket: 'paysync-329b1.firebasestorage.app',
    measurementId: 'G-E5MNQSB9B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHbZuZ8rISLE6MgzeIm7tLavjAy-1evTQ',
    appId: '1:133788893267:android:ec2fe672b92136de0b06a6',
    messagingSenderId: '133788893267',
    projectId: 'paysync-329b1',
    storageBucket: 'paysync-329b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLbWzPSXrplMfZax0swPdvx87jmUcIhp8',
    appId: '1:133788893267:ios:8cc628350f4c1ea80b06a6',
    messagingSenderId: '133788893267',
    projectId: 'paysync-329b1',
    storageBucket: 'paysync-329b1.firebasestorage.app',
    iosBundleId: 'com.example.paysync',
  );
}
